[workspace]
members = ["forge", "web"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"


[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
geo = { version = "0.33", features = ["serde"] }
osmpbfreader = { version = "0.19", features = ["serde"] }
rstar = { version = "0.13", features = ["serde"] }
